import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        surface: "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#0052de",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-primary-container": "#fefcff",
        "surface-container": "#ededf9",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c45100",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#f0f0fc",
        "inverse-surface": "#2e3039",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3ff",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        tertiary: "#9d3f00",
        "tertiary-fixed-dim": "#ffb693",
        "on-tertiary-fixed-variant": "#7a2f00",
        "on-secondary-fixed": "#131b2e",
        "inverse-primary": "#b4c4ff",
        "surface-dim": "#d9d9e5",
        muted: "#64748b",
        "on-primary-fixed-variant": "#003daa",
        "on-primary-fixed": "#00174c",
        primary: "#004fd9",
        "on-background": "#191b24",
        "surface-container-highest": "#e1e1ee",
        "primary-container": "#2e69f9",
        "on-tertiary-fixed": "#351000",
        background: "#faf8ff",
        secondary: "#565e74",
        "primary-fixed-dim": "#b4c4ff",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed": "#ffdbcc",
        "border-subtle": "#e2e8f0",
        "on-secondary-fixed-variant": "#3f465c",
        canvas: "#f8fafc",
        "secondary-container": "#dae2fd",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e7f3",
        "on-secondary-container": "#5c647a",
        outline: "#737687",
        "on-surface": "#191b24",
        "outline-variant": "#c3c5d8",
        "surface-bright": "#faf8ff",
        "surface-variant": "#e1e1ee",
        "marker-blue": "var(--marker-blue)",
        "marker-red": "var(--marker-red)",
        "marker-green": "var(--marker-green)",
        "marker-slate": "var(--marker-slate)",
        highlighter: "var(--highlighter)",
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "margin-page": "1rem",
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        marker: ["Kalam", "cursive"],
      },
      fontSize: {
        "label-mono": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "800" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "1.4", fontWeight: "700" },
        ],
        "body-md": [
          "14px",
          { lineHeight: "1.5", fontWeight: "500" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
